# Generated by Django 6.0.1 on 2026-01-07 07:16

from django.db import migrations


def seed_qscore(apps, schema_editor):
    Evaluator = apps.get_model('ratings_service', 'Evaluator')
    Evaluator.objects.get_or_create(
        name='qscore_v0',
        version='0.1.0',
        defaults={
            'config_json': {
                'weights': {'wc': 0.4, 'wh': 0.4, 'wp': 0.2},
                'rating_scale': {'min': 1, 'max': 5},
                'guardrail_tag': 'guardrails',
            }
        },
    )


def unseed_qscore(apps, schema_editor):
    Evaluator = apps.get_model('ratings_service', 'Evaluator')
    Evaluator.objects.filter(name='qscore_v0', version='0.1.0').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_qscore, unseed_qscore),
    ]
