# Generated by Django 6.0.1 on 2026-01-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_service', '0003_prompt_revert_and_drop_version'),
        ('history_service', '0002_update_history_models'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
